CREATE TABLE `account` (
  `account_cd` varchar(50) NOT NULL,
  `account_used_name` varchar(50) NOT NULL,
  `used_detail` varchar(50) DEFAULT NULL,
  `account_name` varchar(50) NOT NULL,
  `account_password` varchar(50) NOT NULL,
  `country_kbn` varchar(10) NOT NULL,
  `facility_kbn` varchar(10) NOT NULL,
  `query1` varchar(10) DEFAULT NULL,
  `answer1` varchar(10) DEFAULT NULL,
  `query2` varchar(10) DEFAULT NULL,
  `answer2` varchar(10) DEFAULT NULL,
  `query3` varchar(10) DEFAULT NULL,
  `answer3` varchar(10) DEFAULT NULL,
  `oldPassword1` varchar(50) DEFAULT NULL,
  `oldPassword2` varchar(50) DEFAULT NULL,
  `oldPassword3` varchar(50) DEFAULT NULL,
  `biko` varchar(100) DEFAULT NULL,
  `create_user` varchar(50) NOT NULL,
  `create_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `update_user` varchar(50) DEFAULT NULL,
  `update_at` timestamp NULL DEFAULT NULL,
  `used_flg` int(11) DEFAULT '0',
  PRIMARY KEY (`account_cd`),
  UNIQUE KEY `idx_tab_kbn_account_cd` (`account_cd`),
  KEY `id_index` (`country_kbn`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8