CREATE TABLE `user` (
  `userCd` varchar(50) NOT NULL,
  `email` varchar(50) NOT NULL,
  `fullName` varchar(50) NOT NULL,
  `firstName` varchar(50) NOT NULL,
  `lastName` varchar(50) NOT NULL,
  `sex` varchar(50) NOT NULL,
  `birth` varchar(50) NOT NULL,
  `tel` varchar(50) NOT NULL,
  `zip` varchar(50) NOT NULL,
  `address` varchar(100) NOT NULL,
  `nutagPref` int(11) NOT NULL,
  `nutagCity` int(11) NOT NULL,
  `sendMailFlg` tinyint(1) DEFAULT NULL,
  `createUser` varchar(50) DEFAULT NULL,
  `createDateTime` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `updateUser` varchar(50) DEFAULT NULL,
  `updateDateTime` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`userCd`,`email`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8